### ISSUE TITLE
Use single 'Keycloak enabled' variable

### ISSUE THREAD

**Issue by arso** [oVirt/ovirt-engine-keycloak#34]
Replace:
`OVESETUP_KEYCLOAK_CORE/enable` (`okkcons.CoreEnv.ENABLE`) from keycloak setup package 
With:
`OVESETUP_CONFIG/keycloakEnabled` (`oengcommcons.KeycloakEnv.KEYCLOAK_ENABLED`)  from engine setup common package.

**Comment by didib** [comment]
grafana? Not OVESETUP_CONFIG/keycloakEnabled ?

**Comment by arso** [comment]
1. 

> grafana? Not OVESETUP_CONFIG/keycloakEnabled ?

You're absolutely right - I must have done some copy paste mistake. Issue description is now fixed

**Comment by arso** [comment]
Done
